/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: EdwinRC (https://sketchfab.com/Edwin3D)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-beach-assets-66c18ecd7a834d4a99dabc46b5ee6e4a
Title: Low Poly Beach Assets
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const Beach = (props) => {
  const { nodes, materials } = useGLTF('/models/beach.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[116.359, -103.319, 80.924]} rotation={[0.432, 0.47, 2.325]} scale={4.216}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['LightBlue-material'].geometry}
            material={materials.LightBlue}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Orange_003-material'].geometry}
            material={materials.Orange_003}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Gray-material'].geometry}
            material={materials.Gray}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Pink-material'].geometry}
            material={materials.Pink}
          />
        </group>
        <group position={[150.837, -41.758, 79.682]} rotation={[0.717, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['White-material'].geometry}
            material={materials.White}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Blue-material'].geometry}
            material={materials.Blue}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Yellow-material'].geometry}
            material={materials.Yellow}
          />
        </group>
        <group position={[142.742, -51.207, 82.11]} scale={0.061}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Yellow-material_1'].geometry}
            material={materials.Yellow}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Red-material'].geometry}
            material={materials.material}
          />
        </group>
        <group position={[55.662, -41.774, 86.474]} rotation={[0, 0, 0.388]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['LightBlue-material_1'].geometry}
            material={materials.LightBlue}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['White-material_1'].geometry}
            material={materials.White}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Black-material'].geometry}
            material={materials.Black}
          />
        </group>
        <group position={[128.409, -44.28, 104.698]} scale={1.631}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Gray-material_1'].geometry}
            material={materials.Gray}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Red-material_1'].geometry}
            material={materials.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Blue-material_1'].geometry}
            material={materials.Blue}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Yellow-material_2'].geometry}
            material={materials.Yellow}
          />
        </group>
        <group
          position={[116.845, -71.345, 90.411]}
          rotation={[0.236, -0.131, -2.811]}
          scale={0.995}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Green-material'].geometry}
            material={materials.Green}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Brown-material'].geometry}
            material={materials.Brown}
          />
        </group>
        <group
          position={[130.728, -73.169, 81.952]}
          rotation={[-0.048, 0.16, -2.942]}
          scale={0.215}>
          <lineSegments geometry={nodes.Object_31.geometry} material={materials.material_0} />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['LB2-material'].geometry}
            material={materials.material_18}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['White-material_2'].geometry}
            material={materials.White}
          />
        </group>
        <group
          position={[128.945, -87.034, 83.108]}
          rotation={[-0.016, -0.048, 2.785]}
          scale={0.215}>
          <lineSegments geometry={nodes.Object_35.geometry} material={materials.material_0} />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['LB2-material_1'].geometry}
            material={materials.material_18}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['White-material_3'].geometry}
            material={materials.White}
          />
        </group>
        <group
          position={[110.083, -114.243, 87.55]}
          rotation={[-3.132, -0.053, 2.194]}
          scale={1.811}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Red-material_2'].geometry}
            material={materials.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Green-material_1'].geometry}
            material={materials.Green}
          />
        </group>
        <group
          position={[118.084, -41.668, 86.613]}
          rotation={[3.116, -0.439, 1.559]}
          scale={1.811}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['LightBlue-material_2'].geometry}
            material={materials.LightBlue}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Blue-material_2'].geometry}
            material={materials.Blue}
          />
        </group>
        <group position={[125.567, -43.433, 93.397]} rotation={[0, 0, 1.893]} scale={0.995}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Green-material_2'].geometry}
            material={materials.Green}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Brown-material_1'].geometry}
            material={materials.Brown}
          />
        </group>
        <group position={[137.097, -116.876, 80.296]} rotation={[0, 0, -2.997]} scale={2.693}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Pink2-material'].geometry}
            material={materials.Pink2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Green-material_3'].geometry}
            material={materials.Green}
          />
        </group>
        <group
          position={[140.756, -120.035, 81.105]}
          rotation={[0.015, 0.627, 3.093]}
          scale={4.216}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Gray-material_2'].geometry}
            material={materials.Gray}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Red-material_3'].geometry}
            material={materials.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Yellow-material_3'].geometry}
            material={materials.Yellow}
          />
        </group>
        <group position={[155.097, -89.19, 101.659]} rotation={[0, 0, 0.731]} scale={1.376}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Green-material_4'].geometry}
            material={materials.Green}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Brown-material_2'].geometry}
            material={materials.Brown}
          />
        </group>
        <group position={[106.618, -21.424, 101.659]} rotation={[0, 0, -3.112]} scale={1.376}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Green-material_5'].geometry}
            material={materials.Green}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Brown-material_3'].geometry}
            material={materials.Brown}
          />
        </group>
        <group position={[102.924, -117.163, 95.856]} rotation={[0, 0, 0.518]} scale={1.231}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Green-material_6'].geometry}
            material={materials.Green}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Brown-material_4'].geometry}
            material={materials.Brown}
          />
        </group>
        <group position={[92.496, -58.169, 79.366]} rotation={[0, 0.146, 1.918]} scale={2.562}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['White-material_4'].geometry}
            material={materials.White}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Black-material_1'].geometry}
            material={materials.Black}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Orange_003-material_1'].geometry}
            material={materials.Orange_003}
          />
        </group>
        <group position={[79.898, -63.341, 80.029]} rotation={[0, -0.222, 0]} scale={2.562}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Pink2-material_1'].geometry}
            material={materials.Pink2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Orange_003-material_2'].geometry}
            material={materials.Orange_003}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Black-material_2'].geometry}
            material={materials.Black}
          />
        </group>
        <group position={[138.351, -38.199, 88.072]} rotation={[0, 1.57, 0]} scale={2.05}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Orange_003-material_3'].geometry}
            material={materials.Orange_003}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['White-material_5'].geometry}
            material={materials.White}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Red-material_4'].geometry}
            material={materials.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Brown-material_5'].geometry}
            material={materials.Brown}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['LightBlue-material_4'].geometry}
            material={materials.LightBlue}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Blue-material_3'].geometry}
            material={materials.Blue}
          />
        </group>
        <group
          position={[127.717, -81.384, 80.988]}
          rotation={[-3.127, 0, -3.1]}
          scale={[-0.241, 0.241, 0.241]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Green-material_7'].geometry}
            material={materials.Green}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Blue-material_4'].geometry}
            material={materials.Blue}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Red-material_5'].geometry}
            material={materials.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['LightBlue-material_5'].geometry}
            material={materials.LightBlue}
          />
        </group>
        <group position={[128.356, -81.574, 82.822]} rotation={[0.013, 0.3, 3.098]} scale={4.216}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Gray-material_3'].geometry}
            material={materials.Gray}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Pink-material_1'].geometry}
            material={materials.Pink}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Blue-material_5'].geometry}
            material={materials.Blue}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['LightBlue-material_6'].geometry}
            material={materials.LightBlue}
          />
        </group>
        <group position={[116.379, -55.323, 79.474]} rotation={[0.065, 0, -1.57]} scale={2.693}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Towel3-material'].geometry}
            material={materials.Towel3}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Yellow-material_4'].geometry}
            material={materials.Yellow}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Blue-material_6'].geometry}
            material={materials.Blue}
          />
        </group>
        <group position={[116.842, -61.696, 79.083]} rotation={[0, 0, -1.575]} scale={2.693}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Towel1-material'].geometry}
            material={materials.Towel1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Towel2-material'].geometry}
            material={materials.Towel2}
          />
        </group>
        <group position={[112.266, -71.022, 80.244]} rotation={[0, 0.555, 0]} scale={1.96}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Yellow-material_5'].geometry}
            material={materials.Yellow}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Red-material_6'].geometry}
            material={materials.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Pink-material_2'].geometry}
            material={materials.Pink}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Blue-material_7'].geometry}
            material={materials.Blue}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['W2-material'].geometry}
          material={materials.material_19}
          position={[101.31, -77.646, 70.204]}
          scale={61.883}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_10.geometry}
          material={materials.material_0}
          position={[78.975, -40.922, 79.823]}
          rotation={[0, 0, -0.93]}
          scale={1.596}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['R1-material'].geometry}
          material={materials.material_17}
          position={[133.479, -27.506, 79.77]}
          rotation={[-2.686, 0.441, -0.118]}
          scale={1.58}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_66.geometry}
          material={materials.material_0}
          position={[101.31, -77.646, 70.204]}
          scale={61.883}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Sand-material'].geometry}
          material={materials.Sand}
          position={[101.179, -77.646, 70.204]}
          scale={61.883}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['LightBlue-material_3'].geometry}
          material={materials.LightBlue}
          position={[101.31, -77.646, 70.204]}
          scale={61.883}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/low_poly_beach_assets.glb')
export default Beach;